/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.employee_gui;

import java.sql.*;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jude Tulel
 */
public class AdminModule extends javax.swing.JFrame {

    /**
     * Creates new form AdminModule
     */
    private static final String username = "root";
    private static final String password = "Azerty_7205";
    private static final String dataConn = "jdbc:mysql://localhost:3306/ems";
    
   Connection sqlConn = null;
   PreparedStatement pst = null;
   ResultSet rs = null;
   int q, i, id, deleteItem;
    public AdminModule() {
        initComponents();
    }
    public void upDateDB(){
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("select * from employee");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
              DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
              RecordTable.setRowCount(0);
            
            while(rs.next()){
                Vector columnData = new Vector();
                
                for (i = 1;i <= q; i++ ){
                    columnData.add(rs.getString("employee_id"));
                    columnData.add(rs.getString("first_name"));
                    columnData.add(rs.getString("surname"));
                    columnData.add(rs.getString("age"));
                    columnData.add(rs.getString("department"));
                    columnData.add(rs.getString("title"));
                    columnData.add(rs.getString("salary"));

           
                }
                RecordTable.addRow(columnData);
                
            } 
           
        }
        catch (Exception ex){
                JOptionPane.showMessageDialog(null, ex);
                }
        }
    
     



  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtFirst_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtEmp_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtSurname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtAge = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jtxtDep = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxttitle = new javax.swing.JTextField();
        jtxtsalary = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jbtnAdd = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnLogout = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel1.setText("ADMINISTRATOR DASHBOARD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("FIRST_NAME");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jtxtFirst_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFirst_nameActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtFirst_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 230, 30));

        jLabel3.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("EMPLOYEE_ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jtxtEmp_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmp_idActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtEmp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 230, 30));

        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("SURNAME");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jtxtSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSurnameActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 230, 30));

        jLabel5.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("AGE");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jtxtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAgeActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 230, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "EMPLOYEE_ID", "FIRST_NAME", "SURNAME", "AGE", "DEPARTMENT", "TITLE", "SALARY"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 700, 140));

        jLabel6.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("DEPARTMENT");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));
        jPanel2.add(jtxtDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 230, 30));

        jLabel7.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 243));
        jLabel7.setText("TITLE");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 243));
        jLabel8.setText("SALARY");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));
        jPanel2.add(jtxttitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 230, 30));
        jPanel2.add(jtxtsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 220, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 740, 530));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnAdd.setText("ADD NEW");
        jbtnAdd.setPreferredSize(new java.awt.Dimension(75, 25));
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 50));

        jbtnUpdate.setText("UPDATE");
        jbtnUpdate.setPreferredSize(new java.awt.Dimension(75, 25));
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, 50));

        jbtnDelete.setText("DELETE");
        jbtnDelete.setPreferredSize(new java.awt.Dimension(75, 25));
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 180, 130, 50));

        jbtnReset.setText("RESET");
        jbtnReset.setPreferredSize(new java.awt.Dimension(75, 25));
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, 50));

        jbtnExit.setText("EXIT");
        jbtnExit.setPreferredSize(new java.awt.Dimension(75, 25));
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 110, 50));

        jbtnLogout.setText("LOG OUT");
        jbtnLogout.setPreferredSize(new java.awt.Dimension(75, 25));
        jbtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogoutActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 110, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 160, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 950, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtEmp_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmp_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmp_idActionPerformed

    private void jtxtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAgeActionPerformed
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
        frame2 = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","EMPLOYEE MANAGEMENT SYSTEM",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
        System.exit(0);}
        
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jtxtSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSurnameActionPerformed
private JFrame frame2;
    private void jbtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogoutActionPerformed
        // TODO add your handling code here:
        frame2 = new JFrame("Logout");
        if (JOptionPane.showConfirmDialog(frame2, "Are you sure you want to logout","Admin",
                JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
        dispose();
        Menu menu = new Menu();
        menu.show();

        }
    }//GEN-LAST:event_jbtnLogoutActionPerformed

    private void jtxtFirst_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFirst_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFirst_nameActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        jtxtEmp_id.setText("");
        jtxtFirst_name.setText("");
        jtxtSurname.setText("");
        jtxtAge.setText("");
        jtxtDep.setText(""); 
        jtxttitle.setText("");
        jtxtsalary.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("insert into employee(first_name,surname,age,employee_id,department,title,salary)value(?,?,?,?,?,?,?)");
            pst.setString(1, jtxtFirst_name.getText());
            pst.setString(2, jtxtSurname.getText());
            pst.setString(3, jtxtAge.getText());
            pst.setString(4, jtxtEmp_id.getText());
            pst.setString(5, jtxtDep.getText());
            pst.setString(6, jtxttitle.getText());
            pst.setString(7, jtxtsalary.getText());
        
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added succesfully");
            upDateDB();
            
        
                
                }catch (ClassNotFoundException ex){
                    java.util.logging.Logger.getLogger(AdminModule.class.getName()).log(java.util.logging.Level.SEVERE,null, ex);
                }catch (SQLException ex){
                    java.util.logging.Logger.getLogger(AdminModule.class.getName()).log(java.util.logging.Level.SEVERE, null , ex);
                }
        

       
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("update employee set first_name=?,surname=?,age=?,employee_id=?,department=?,title=?,salary=? where employee_id=?");
            pst.setString(1, jtxtFirst_name.getText());
            pst.setString(2, jtxtSurname.getText());
            pst.setString(3, jtxtAge.getText());
            pst.setString(4, jtxtEmp_id.getText());
            pst.setString(5, jtxtDep.getText());
            pst.setString(6, jtxttitle.getText());
            pst.setString(7, jtxtsalary.getText());
                    
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Updated succesfully");
            upDateDB();
            
        
                
                }catch (ClassNotFoundException ex){
                    java.util.logging.Logger.getLogger(AdminModule.class.getName()).log(java.util.logging.Level.SEVERE,null, ex);
                }catch (SQLException ex){
                    java.util.logging.Logger.getLogger(AdminModule.class.getName()).log(java.util.logging.Level.SEVERE, null , ex);
                }
       
        
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            int SelectedRows =  jTable1.getSelectedRow();
            jtxtFirst_name.setText(RecordTable.getValueAt(SelectedRows,1).toString());
            jtxtSurname.setText(RecordTable.getValueAt(SelectedRows,2).toString());
            jtxtAge.setText(RecordTable.getValueAt(SelectedRows,3).toString());
            jtxtEmp_id.setText(RecordTable.getValueAt(SelectedRows,4).toString());
            jtxtDep.setText(RecordTable.getValueAt(SelectedRows,5).toString());
            jtxttitle.setText(RecordTable.getValueAt(SelectedRows,6).toString());
            jtxtsalary.setText(RecordTable.getValueAt(SelectedRows, 7).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        try
        {
        
            id = Integer.parseInt(RecordTable.getValueAt(SelectedRows,0).toString());
            
            deleteItem = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete the record","WARNING",JOptionPane.YES_NO_OPTION);
            if (deleteItem == JOptionPane.YES_OPTION){
                Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn,username,password);
                pst = sqlConn.prepareStatement("delete from employee where employee_id =?");
               // pst.setInt(, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Records Updated");
                upDateDB();
                jtxtEmp_id.setText("");
                jtxtFirst_name.setText("");
                jtxtSurname.setText("");
                jtxtAge.setText("");
                jtxtDep.setText("");
                
                }
        }catch (ClassNotFoundException ex){
                    java.util.logging.Logger.getLogger(AdminModule.class.getName()).log(java.util.logging.Level.SEVERE,null, ex);
        }catch (SQLException ex){
            System.err.println(ex);
                
            }
            
        
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnLogout;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField jtxtAge;
    private javax.swing.JTextField jtxtDep;
    private javax.swing.JTextField jtxtEmp_id;
    private javax.swing.JTextField jtxtFirst_name;
    private javax.swing.JTextField jtxtSurname;
    private javax.swing.JTextField jtxtsalary;
    private javax.swing.JTextField jtxttitle;
    // End of variables declaration//GEN-END:variables
}
