/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.employee_gui;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jude Tulel
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     * 
     */
    private static final String username = "root";
    private static final String password = "Azerty_7205";
    private static final String dataConn = "jdbc:mysql://localhost:3306/ems";
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usrName = new javax.swing.JTextField();
        passWord = new javax.swing.JPasswordField();
        login_btn = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        login_head = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("UserName");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 47, -1, 29));

        jLabel2.setBackground(new java.awt.Color(153, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 88, -1, -1));
        getContentPane().add(usrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 51, 229, -1));
        getContentPane().add(passWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 89, 229, -1));

        login_btn.setBackground(new java.awt.Color(0, 51, 204));
        login_btn.setFont(new java.awt.Font("Univers", 1, 18)); // NOI18N
        login_btn.setForeground(new java.awt.Color(204, 255, 255));
        login_btn.setText("Login");
        login_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(153, 255, 255), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 204, 204)));
        login_btn.setMaximumSize(new java.awt.Dimension(54, 28));
        login_btn.setMinimumSize(new java.awt.Dimension(54, 28));
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        getContentPane().add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 129, -1, -1));

        reset_btn.setBackground(new java.awt.Color(0, 51, 204));
        reset_btn.setFont(new java.awt.Font("Univers 55", 1, 18)); // NOI18N
        reset_btn.setForeground(new java.awt.Color(204, 255, 255));
        reset_btn.setText("Reset");
        reset_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(153, 255, 255), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 255, 255)));
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        getContentPane().add(reset_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 130, 61, 29));

        login_head.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        login_head.setText("ADMINISTRATOR LOGIN ");
        getContentPane().add(login_head, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 12, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        // TODO add your handling code here:
        /*reset Button resets all values*/
        usrName.setText("");
        passWord.setText("");
    }//GEN-LAST:event_reset_btnActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(dataConn,username,password); {
                String username = usrName.getText();
                String password = passWord.getText();
                
                java.sql.Statement stm = con.createStatement();
                String sql = "select * from admin where username='"+username+"' and password='"+password+"'";
                ResultSet rs = stm.executeQuery(sql);
                
                if (rs.next()){
                    //password correct open Admin
                    dispose();//closes login
                    AdminModule admin = new AdminModule();
                    admin.show();
                    
                }else{
                    //if username and password is wrong
                    JOptionPane.showMessageDialog(this,"Username Or Password is wrong");
                    usrName.setText("");
                    passWord.setText("");
                }
            }
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
            System.out.println(e.getMessage());
            
            
        }
    }//GEN-LAST:event_login_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton login_btn;
    private javax.swing.JLabel login_head;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JButton reset_btn;
    private javax.swing.JTextField usrName;
    // End of variables declaration//GEN-END:variables
}
